### ISSUE TITLE
The Moe-dark scheme looks different

### ISSUE THREAD

**Issue by examinedliving** [joonro/ConEmu-Color-Themes#3]
It doesn't look anything like this picture in my terminal.  Judging by the color values in the xml file, they don't look like they could possibly yield the colors in the picture you posted.  Am I missing something; or perhaps, the wrong photo/xml file has been uploaded to this repo?

**Comment by joonro** [comment]
I'm sorry that you are having problems. I just checked my `ConEmu.xml` and they have the same values as `moe-dark.xml`, so they are correct. 

If you are talking about not getting all the fancy colors that I have in the screenshots, please see my blog post at http://joonro.github.io/blog/posts/powershell-customizations.html  for customizations, as described in the README.

Otherwise please attach more information so I can see what is going on.

**Comment by examinedliving** [comment]
Alright - I tried again entering it by hand.  And it works.  Don't know what I did wrong, but its fixed now.  Sorry about that.

**Comment by joonro** [comment]
No worries. The xml files have colors in `0xBBGGRR` (hex) format and that may have been the source of the confusion.
