### ISSUE TITLE
What term are you using?

### ISSUE THREAD

**Issue by ErraticFox** [joonro/ConEmu-Color-Themes#4]
What terminal are you using with ConEmu? I'm using Cygwin with ConEmu, though my path and name don't use colors for some reason.

I've tried MinGW bash, Windows 10 Bash, Git Bash, CMD, and PowerShell and none of them color the path or user and machine name.

**Comment by joonro** [comment]
Hi - I mainly use PowerShell - but to get these colors you need some customization. Please read the first part of the introduction.

**Comment by ErraticFox** [comment]
Which part? The `Get-ChildItem-Color` or `posh-git`? If this is the case, would I just be able to edit the PS1 string and get the color on them if I'm wanting to use Win10 Bash?

**Comment by joonro** [comment]
`posh-git` gives you the prompt, and `Get-ChildItem-Color` will give you coloring in `ls` (`Get-ChildItem`). If you use bash, then you have to customize your prompt accordingly (e.g., in `.bashrc`) to get the coloring, since once you start bash, PowerShell will not be applicable anymore. I'm sure you will be able to find color themes for your bash prompt that you like somewhere.

These color schemes basically change what color will be shown for color `purple` for example, and it's up to you to specify which color to use for which item (e.g., an item in your prompt). Hopefully this makes sense.
